### ISSUE TITLE
Add examples/documentation about the template

### ISSUE THREAD

**Issue by gwmensink** [DanielThomassen/CS-ConfigurationSectionGenerator#1]
When I try to  a config section with this template, I get an error:

```
<filters>
    <filter name="nameFilter" type="f.q.n, f.q" />
    <filter name="sizeFilter" type="f.q.n, f.q" />
 </filters>
```

This makes sense, because your root element cannot be a collection and a section at once. Perhaps it would be good to add some documentation about the templates, or provide some example configs.

**Comment by DanielThomassen** [comment]
Documentation has been updated to include some examples
